theme: minima
title: The Riddles Project
author: McGill University Library
email: timelessriddles@gmail.com
description: The Riddles Project is an ROAAr project dedicated to transcribing, solving, and researching riddles in early manuscripts.

header_pages:
  - blog.md

show_excerpts: true

minima:
  social_links:
    github: riddlesproject
    twitter: Time1essRiddles
    facebook: timelessriddles