theme: minima
title: The Riddle Project
author: McGill University Library
email: timelessriddles@gmail.com
description: The Riddle Project is an ROAAr project dedicated to transcribing, solving, and researching riddles in early manuscripts.

header_pages:
  - interactive-map.md
  - story-map.md
  - blog.md
  - about.md

show_excerpts: true

minima:
  social_links:
    github: riddleproject
    twitter: Time1essRiddles
    facebook: timelessriddles
