theme: minima
title: The Riddle Project
author: McGill University Library
email: theriddleprojectmcgill@gmail.com
description: The Riddle Project is an ROAAr project dedicated to transcribing, solving, and researching riddles in early manuscripts.

header_pages:
  - exhibition.md
  - maps.md
  - blog.md
  - about.md

show_excerpts: true

minima:
  social_links:
    github: riddleproject
    twitter: Time1essRiddles
    facebook: timelessriddles
    instagram: riddles_in_time
 
