theme: minima
title: The Riddles Project
home.title: The Riddles Project
author: McGill University Library
email: timelessriddles@gmail.com
description: The Riddles Project is a ROAAr project dedicated to transcribing, solving, and researching riddles in early manuscripts.

header_pages:
  - filters.html
  - story.html

show_excerpts: true

minima:
  date_format: "%b %-d, %Y"
  social_links:
    github:  riddlesproject